workload_path: ../../src/Workloads/Redset/workload1h-5m-30s_186_8_1.csv
workload_name: workload1h-5m-30s_186_8_1
host: localhost
databend_port: 8000
prometheus_port: 9090
count_limit: 1000
time_limit: 270
use_operator: 1
wait: 8
interval: 30
query:
- redbench
db:
- imdb
op_scale: 100
initial_count: 10
use_duration: 0
